# Version: 2
# This Service exposes the API internally on port 1234.
# The Ingress (created later) will point to this Service to expose it to the world.

apiVersion: v1
kind: Service
metadata:
  name: podverse-api
spec:
  type: ClusterIP
  selector:
    app: podverse-api
  ports:
    - name: http
      port: 1234
      targetPort: 1234
      protocol: TCP
