.PHONY: sandbox_validate_init
sandbox_validate_init: config/podverse-sandbox-db.env config/podverse-sandbox-queue-amtp.env config/podverse-sandbox-workers.env config/podverse-sandbox-api.env

config/podverse-sandbox-db.env:
	@echo "Missing: $@"
	@echo "Copying from example file"
	cp ./$@.example ./$@

config/podverse-sandbox-queue-amtp.env:
	@echo "Missing: $@"
	@echo "Copying from example file"
	cp ./$@.example ./$@

config/podverse-sandbox-workers.env:
	@echo "Missing: $@"
	@echo "Copying from example file"
	cp ./$@.example ./$@

config/podverse-sandbox-api.env:
	@echo "Missing: $@"
	@echo "Copying from example file"
	cp ./$@.example ./$@

.PHONY: sandbox_db_up
sandbox_db_up: config/podverse-sandbox-db.env
	docker compose -f docker-compose/sandbox/db/docker-compose.yml up podverse_sandbox_db -d

.PHONY: sandbox_db_down
sandbox_db_down:
	docker compose -f docker-compose/sandbox/db/docker-compose.yml stop podverse_sandbox_db
	docker compose -f docker-compose/sandbox/db/docker-compose.yml rm -f podverse_sandbox_db
	docker images "postgres" --format "{{.Repository}}:{{.Tag}}" | xargs -r docker image rm -f || true

.PHONY: sandbox_queue_atmp_up
sandbox_queue_atmp_up: config/podverse-sandbox-queue-amtp.env
	docker compose -f docker-compose/sandbox/queue/docker-compose.yml up podverse_sandbox_queue_atmp -d

.PHONY: sandbox_queue_atmp_down
sandbox_queue_atmp_down:
	docker compose -f docker-compose/sandbox/queue/docker-compose.yml down --remove-orphans --rmi all

.PHONY: sandbox_workers_up
sandbox_workers_up: config/podverse-sandbox-workers.env
	docker compose -f docker-compose/sandbox/workers/docker-compose.yml pull podverse_sandbox_workers

.PHONY: sandbox_workers_down
sandbox_workers_down:
	docker compose -f docker-compose/sandbox/workers/docker-compose.yml down --remove-orphans --rmi all

.PHONY: sandbox_api_up
sandbox_api_up: config/podverse-sandbox-api.env
	docker compose -f docker-compose/sandbox/srv/docker-compose.yml up podverse_sandbox_api -d

.PHONY: sandbox_api_down
sandbox_api_down:
	docker compose -f docker-compose/sandbox/srv/docker-compose.yml stop podverse_sandbox_api
	docker compose -f docker-compose/sandbox/srv/docker-compose.yml rm -f podverse_sandbox_api
	docker images "ghcr.io/podverse/podverse-api/podverse-api" --format "{{.Repository}}:{{.Tag}}" | xargs -r docker image rm -f || true

.PHONY: sandbox_all_up
sandbox_all_up:
	$(MAKE) sandbox_validate_init
	$(MAKE) sandbox_db_up
	$(MAKE) sandbox_queue_up
	$(MAKE) sandbox_workers_up
	$(MAKE) sandbox_api_up

.PHONY: sandbox_all_down
sandbox_all_down:
	$(MAKE) sandbox_api_down
	$(MAKE) sandbox_workers_down
	$(MAKE) sandbox_queue_down
	$(MAKE) sandbox_db_down
