.PHONY: sandbox_validate_init
sandbox_validate_init: config/podverse-sandbox-db.env config/podverse-sandbox-queue-amtp.env config/podverse-sandbox-workers.env config/podverse-sandbox-api.env config/podverse-sandbox-web.env

config/podverse-sandbox-db.env:
	@echo "Missing: $@"
	@echo "Copying from example file"
	cp ./$@.example ./$@

config/podverse-sandbox-queue-amtp.env:
	@echo "Missing: $@"
	@echo "Copying from example file"
	cp ./$@.example ./$@

config/podverse-sandbox-workers.env:
	@echo "Missing: $@"
	@echo "Copying from example file"
	cp ./$@.example ./$@

config/podverse-sandbox-api.env:
	@echo "Missing: $@"
	@echo "Copying from example file"
	cp ./$@.example ./$@

config/podverse-sandbox-web.env:
	@echo "Missing: $@"
	@echo "Copying from example file"
	cp ./$@.example ./$@

.PHONY: sandbox_db_up
sandbox_db_up: config/podverse-sandbox-db.env
	docker compose -f docker-compose/sandbox/db/docker-compose.yml up podverse_sandbox_db -d

.PHONY: sandbox_db_down
sandbox_db_down:
	docker compose -f docker-compose/sandbox/db/docker-compose.yml down --remove-orphans --rmi all

.PHONY: sandbox_queue_amtp_up
sandbox_queue_amtp_up: config/podverse-sandbox-queue-amtp.env
	docker compose -f docker-compose/sandbox/queue-amtp/docker-compose.yml up podverse_sandbox_queue_amtp -d

.PHONY: sandbox_queue_amtp_down
sandbox_queue_amtp_down:
	docker compose -f docker-compose/sandbox/queue-amtp/docker-compose.yml down --remove-orphans --rmi all

.PHONY: sandbox_workers_up
sandbox_workers_up: config/podverse-sandbox-workers.env
	docker compose -f docker-compose/sandbox/workers/docker-compose.yml pull podverse_sandbox_workers

.PHONY: sandbox_workers_down
sandbox_workers_down:
	docker compose -f docker-compose/sandbox/workers/docker-compose.yml down --remove-orphans --rmi all

.PHONY: sandbox_api_up
sandbox_api_up: config/podverse-sandbox-api.env
	docker compose -f docker-compose/sandbox/api/docker-compose.yml up podverse_sandbox_api -d

.PHONY: sandbox_api_down
sandbox_api_down:
	docker compose -f docker-compose/sandbox/api/docker-compose.yml down --remove-orphans --rmi all

.PHONY: sandbox_web_up
sandbox_web_up: config/podverse-sandbox-web.env
	docker compose -f docker-compose/sandbox/web/docker-compose.yml up podverse_sandbox_web -d

.PHONY: sandbox_web_down
sandbox_web_down:
	docker compose -f docker-compose/sandbox/web/docker-compose.yml down --remove-orphans --rmi all

.PHONY: sandbox_all_down
sandbox_all_down:
	$(MAKE) sandbox_web_down
	$(MAKE) sandbox_api_down
	$(MAKE) sandbox_workers_down
	$(MAKE) sandbox_queue_amtp_down
	$(MAKE) sandbox_db_down
