.PHONY: local_validate_init
local_validate_init: config/podverse-local-db.env config/podverse-local-queue-amtp.env config/podverse-local-workers.env config/podverse-local-api.env

config/podverse-local-db.env:
	@echo "Missing: $@"
	@echo "Copying from example file"
	cp ./$@.example ./$@

config/podverse-local-queue-amtp.env:
	@echo "Missing: $@"
	@echo "Copying from example file"
	cp ./$@.example ./$@

config/podverse-local-workers.env:
	@echo "Missing: $@"
	@echo "Copying from example file"
	cp ./$@.example ./$@

config/podverse-local-api.env:
	@echo "Missing: $@"
	@echo "Copying from example file"
	cp ./$@.example ./$@

.PHONY: local_db_up
local_db_up: config/podverse-local-db.env
	docker compose -f docker-compose/local/db/docker-compose.yml up podverse_local_db -d

.PHONY: local_db_down
local_db_down:
	docker compose -f docker-compose/local/db/docker-compose.yml down --remove-orphans --rmi all

.PHONY: local_queue_amtp_up
local_queue_amtp_up: config/podverse-local-queue-amtp.env
	docker compose -f docker-compose/local/queue-amtp/docker-compose.yml up podverse_local_queue_amtp -d

.PHONY: local_queue_amtp_down
local_queue_amtp_down:
	docker compose -f docker-compose/local/queue-amtp/docker-compose.yml down --remove-orphans --rmi all

.PHONY: local_workers_up
local_workers_up: config/podverse-local-workers.env
	docker compose -f docker-compose/local/workers/docker-compose.yml pull podverse_local_workers

.PHONY: local_workers_down
local_workers_down:
	docker compose -f docker-compose/local/workers/docker-compose.yml down --remove-orphans --rmi all

.PHONY: local_api_up
local_api_up: config/podverse-local-api.env
	docker compose -f docker-compose/local/api/docker-compose.yml up podverse_local_api -d

.PHONY: local_api_down
local_api_down:
	docker compose -f docker-compose/local/api/docker-compose.yml down --remove-orphans --rmi all

.PHONY: local_web_up
local_web_up: config/podverse-local-web.env
	docker compose -f docker-compose/local/web/docker-compose.yml up podverse_local_web -d

.PHONY: local_web_down
local_web_down:
	docker compose -f docker-compose/local/web/docker-compose.yml down --remove-orphans --rmi all

.PHONY: local_all_down
local_all_down:
	$(MAKE) local_web_down
	$(MAKE) local_api_down
	$(MAKE) local_workers_down
	$(MAKE) local_queue_down
	$(MAKE) local_db_down
