volumes:
  rabbitmq_data:

networks:
  podverse_local_network:
    external: true

services:

  podverse_local_queue_amtp:
    image: rabbitmq:3-management
    container_name: podverse_local_queue_amtp
    env_file:
      - ../../../config/podverse-local-queue-amtp.env
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - podverse_local_network
    restart: always
    shm_size: 1gb
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    logging:
      driver: 'json-file'
      options:
        max-file: '1'
        max-size: '50m'
