apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-recent-feeds.yaml
  - 02-archive-all.yaml
  - 03-reports.yaml
  - 04-dead-feeds-merge.yaml
  - 05-delete-outdated.yaml
