# Source: Jenkinsfile.aux_workers_mq_rss_run_dlq_consumer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-consumer-dlq
  namespace: podverse-alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-consumer-dlq
  template:
    metadata:
      labels:
        app: worker-consumer-dlq
    spec:
      containers:
      - name: worker
        image: ghcr.io/podverse/podverse-workers/podverse-workers:latest
        command: ["npm", "run", "mq_rss_run_dlq_consumer"]
        envFrom:
        - configMapRef:
            name: podverse-workers-config
        - secretRef:
            name: podverse-workers-secret
        volumeMounts:
        - name: firebase-config
          mountPath: /opt/config/firebase-key.json
          subPath: firebase-key.json
          readOnly: true
      volumes:
      - name: firebase-config
        secret:
          secretName: podverse-workers-firebase-secret
