# Version: 2 (Added DB Secret Ref)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-parser-normal
  namespace: podverse-alpha
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-parser-normal
  template:
    metadata:
      labels:
        app: worker-parser-normal
    spec:
      containers:
      - name: worker
        image: ghcr.io/podverse/podverse-workers/podverse-workers:latest
        command: ["npm", "run", "mq_rss_run_parser", "--", "-q", "rss-normal"]
        envFrom:
        - configMapRef:
            name: podverse-workers-config
        - secretRef:
            name: podverse-workers-secret
        # Load DB secrets (DB_READ_PASSWORD, etc.)
        - secretRef:
            name: podverse-db-secret
            
        volumeMounts:
        - name: firebase-config
          mountPath: /opt/config/firebase-key.json
          subPath: firebase-key.json
          readOnly: true
      volumes:
      - name: firebase-config
        secret:
          secretName: podverse-workers-firebase-secret
