# Version: 3
# Root Application (App of Apps Pattern)
# This file tells ArgoCD to look at the 'apps/' directory to find other applications to deploy.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podverse-alpha
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project within ArgoCD for grouping apps
  project: podverse
  source:
    repoURL: https://github.com/podverse/podverse-ops.git
    targetRevision: feature/k3s02
    
    # This path points to where the "Child" App manifests are stored
    path: k8s/alpha/apps
    
    directory:
      recurse: true
      
  destination:
    server: https://kubernetes.default.svc
    namespace: podverse-alpha
  
  # Sync Policy: Automated means ArgoCD will watch Git and apply changes immediately.
  syncPolicy:
    automated:
      prune: true     # Deletes resources in K8s if they are removed from Git
      selfHeal: true  # Overwrites manual 'kubectl edit' changes to match Git
    syncOptions:
      - CreateNamespace=true