apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 03-configmap.yaml
  - consumer-dlq.yaml
  - listener-live.yaml
  - parser-live.yaml
  - parser-normal.yaml
  - parser-ondemand.yaml

