apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 03-configmap.yaml
  - consumer-dlq.yaml
  - 04-listener-live.yaml
  - 05-parser-live.yaml
  - 06-parser-normal.yaml
  - 07-parser-ondemand.yaml