apiVersion: v1
kind: Secret
metadata:
  name: podverse-workers-secret
  namespace: podverse-alpha
type: Opaque
stringData:
  PODCAST_INDEX_AUTH_KEY: "CHANGE_ME"
  PODCAST_INDEX_SECRET_KEY: "CHANGE_ME"
