apiVersion: v1
kind: Secret
metadata:
  name: podverse-db-secret
  namespace: podverse-alpha
type: Opaque
stringData:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "CHANGE_ME"
  POSTGRES_READ_PASSWORD: "CHANGE_ME"
  POSTGRES_READ_WRITE_PASSWORD: "CHANGE_ME"
