apiVersion: v1
kind: Secret
metadata:
  name: podverse-mq-secret
  namespace: podverse-alpha
type: Opaque
stringData:
  ARTEMIS_USER: "admin"
  ARTEMIS_PASSWORD: "CHANGE_ME"
  MESSAGE_QUEUE_USERNAME: "admin"
  MESSAGE_QUEUE_PASSWORD: "CHANGE_ME"
