apiVersion: v1
kind: Secret
metadata:
  name: podverse-workers-firebase-secret
  namespace: podverse-alpha
type: Opaque
stringData:
  firebase-key.json: |
    {
      "type": "service_account",
      "project_id": "example-project",
      "private_key": "-----BEGIN PRIVATE KEY-----\n..."
    }
