#!/bin/bash
set -e

# Ensure required env vars exist
: "${POSTGRES_READ_PASSWORD:?Missing POSTGRES_READ_PASSWORD}"
: "${POSTGRES_READ_WRITE_PASSWORD:?Missing POSTGRES_READ_WRITE_PASSWORD}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'read') THEN
        EXECUTE format('CREATE USER read WITH PASSWORD %L', '${POSTGRES_READ_PASSWORD}');
    END IF;
END
\$\$;

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'read_write') THEN
        EXECUTE format('CREATE USER read_write WITH PASSWORD %L', '${POSTGRES_READ_WRITE_PASSWORD}');
    END IF;
END
\$\$;

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO read, read_write;
GRANT USAGE ON SCHEMA public TO read, read_write;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO read;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO read;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO read_write;
GRANT SELECT, USAGE, UPDATE ON ALL SEQUENCES IN SCHEMA public TO read_write;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO read;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO read;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO read_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, USAGE, UPDATE ON SEQUENCES TO read_write;
SQL