volumes:
  artemis_data:

networks:
  podverse_alpha_network:
    external: true

services:

  podverse_alpha_mq:
    image: apache/activemq-artemis:2.37.0
    container_name: podverse_alpha_mq
    env_file:
      - ../../../config/podverse-alpha-mq.env
    ports:
      - 127.0.0.1:5672:5672   # AMQP 1.0
      - 127.0.0.1:8161:8161   # Web console
    networks:
      - podverse_alpha_network
    restart: unless-stopped
    volumes:
      - artemis_data:/var/lib/activemq-artemis
    logging:
      driver: "syslog"
      options:
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
