volumes:
  artemis_data:

networks:
  podverse_sandbox_network:
    external: true

services:

  podverse_sandbox_mq:
    image: apache/activemq-artemis:2.37.0
    container_name: podverse_sandbox_mq
    env_file:
      - ../../../config/podverse-sandbox-mq.env
    ports:
      - '5672:5672'   # AMQP 1.0
      - '8161:8161'   # Web console
    networks:
      - podverse_sandbox_network
    restart: always
    shm_size: 1gb
    volumes:
      - artemis_data:/var/lib/activemq-artemis
    logging:
      driver: "syslog"
      options:
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
