PGPASSWORD='mysecretpw' psql -h 0.0.0.0 -p 5432 -U postgres -c "COPY episodes(id, title, "\"pastHourTotalUniquePageviews\"", "\"pastDayTotalUniquePageviews\"", "\"pastWeekTotalUniquePageviews\"", "\"pastMonthTotalUniquePageviews\"", "\"pastYearTotalUniquePageviews\"", "\"pastAllTimeTotalUniquePageviews\"") TO stdout DELIMITER ',' CSV;" > /home/mitch/podverse-ops/manticore/episode_export.csv;
awk '{printf "%s,%s\n", NR,$0}' /home/mitch/podverse-ops/manticore/episode_export.csv > /home/mitch/podverse-ops/manticore/episode_export_with_serial_column.csv;
rm /home/mitch/podverse-ops/manticore/episode_export.csv;
split -l 1500000 /home/mitch/podverse-ops/manticore/episode_export_with_serial_column.csv /home/mitch/podverse-ops/manticore/episode_export_csvs/episode_export_ -d --additional-suffix=.csv
docker exec -it podverse_manticore_prod gosu manticore indexer idx_author --rotate;
docker exec -it podverse_manticore_prod gosu manticore indexer idx_media_ref --rotate;
docker exec -it podverse_manticore_prod gosu manticore indexer idx_playlist --rotate;
docker exec -it podverse_manticore_prod gosu manticore indexer idx_podcast --rotate;
docker exec -it podverse_manticore_prod gosu manticore indexer idx_episode idx_episode_01 idx_episode_02 idx_episode_03 idx_episode_04 idx_episode_05 idx_episode_06 idx_episode_07 idx_episode_08 idx_episode_09 idx_episode_10 idx_episode_11 idx_episode_12 idx_episode_13 idx_episode_14 idx_episode_15 idx_episode_16 idx_episode_17 idx_episode_18 idx_episode_19 idx_episode_20 idx_episode_21 idx_episode_22 idx_episode_23 idx_episode_24 idx_episode_25 idx_episode_26 idx_episode_27 idx_episode_28 idx_episode_29 idx_episode_30 idx_episode_31 idx_episode_32 idx_episode_33 idx_episode_34 idx_episode_35 idx_episode_36 idx_episode_37 idx_episode_38 idx_episode_39 idx_episode_40 idx_episode_41 idx_episode_42 idx_episode_43 idx_episode_44 idx_episode_45 idx_episode_46 idx_episode_47 idx_episode_48 idx_episode_49 idx_episode_50 idx_episode_51 idx_episode_52 idx_episode_53 idx_episode_54 idx_episode_55 idx_episode_56 idx_episode_57 idx_episode_58 idx_episode_59 idx_episode_60 idx_episode_61 idx_episode_62 idx_episode_63 idx_episode_64 idx_episode_65 idx_episode_66 idx_episode_67 idx_episode_68 idx_episode_69 idx_episode_70 idx_episode_71 idx_episode_72 idx_episode_73 idx_episode_74 idx_episode_75 idx_episode_76 idx_episode_77 idx_episode_78 idx_episode_79 idx_episode_80 idx_episode_81 idx_episode_82 idx_episode_83 idx_episode_84 idx_episode_85 idx_episode_86 idx_episode_87 idx_episode_88 idx_episode_89 idx_episode_90 idx_episode_91 idx_episode_92 idx_episode_93 idx_episode_94 idx_episode_95 idx_episode_96 idx_episode_97 idx_episode_98 idx_episode_99 --merge;
