networks:
  podverse_local_network:
    external: true

services:

  podverse_local_workers:
    image: podverse-workers:latest
    container_name: podverse_local_workers
    env_file:
      - ../../../config/podverse-local-workers.env
    networks:
      - podverse_local_network
    logging:
      driver: 'json-file'
      options:
        max-file: '1'
        max-size: '50m'
    volumes:
      - ../../../config/firebase/firebase-key.json:/opt/config/firebase-key.json:ro
      - ../../../logs/workers:/opt/logs
    stop_grace_period: 5m
