networks:
  podverse_local_network:
    external: true

services:

  podverse_local_workers:
    image: ghcr.io/podverse/podverse-workers/podverse-workers:5.1.4-alpha.1
    container_name: podverse_local_workers
    env_file:
      - ../../../config/podverse-local-workers.env
    networks:
      - podverse_local_network
    shm_size: 1gb
    logging:
      driver: 'json-file'
      options:
        max-file: '1'
        max-size: '50m'
    volumes:
      - ../../../config/firebase/firebase-key.json:/app/config/firebase-key.json:ro
