/usr/bin/git clone https://github.com/podverse/podcast-db.git
/usr/bin/git clone https://github.com/podverse/podverse-admin.git
/usr/bin/git clone https://github.com/podverse/podverse-api.git
/usr/bin/git clone https://github.com/podverse/podverse-ios.git
/usr/bin/git clone https://github.com/podverse/podverse-ops.git
/usr/bin/git clone https://github.com/podverse/podverse-qa.git
/usr/bin/git clone https://github.com/podverse/podverse-rn.git
/usr/bin/git clone https://github.com/podverse/podverse-ui.git
/usr/bin/git clone https://github.com/podverse/podverse-web.git
