/usr/bin/docker stop podverse_api_parser_worker_priority_1
/usr/bin/docker stop podverse_api_parser_worker_priority_2
/usr/bin/docker stop podverse_api_parser_worker_priority_3
/usr/bin/docker stop podverse_api_parser_worker_priority_4
/usr/bin/docker stop podverse_api_parser_worker_priority_5