/usr/bin/docker stop podverse_api_parser_worker_1
/usr/bin/docker stop podverse_api_parser_worker_2
/usr/bin/docker stop podverse_api_parser_worker_3
/usr/bin/docker stop podverse_api_parser_worker_4
/usr/bin/docker stop podverse_api_parser_worker_5
/usr/bin/docker stop podverse_api_parser_worker_6
/usr/bin/docker stop podverse_api_parser_worker_7
/usr/bin/docker stop podverse_api_parser_worker_8
/usr/bin/docker stop podverse_api_parser_worker_9_live
/usr/bin/docker stop podverse_api_parser_worker_10_live
