networks:
  podverse_sandbox_network:
    external: true

volumes:
  podverse_sandbox_keyvaldb_data:

services:
  podverse_sandbox_keyvaldb:
    image: valkey/valkey:9.0.1
    container_name: podverse_sandbox_keyvaldb
    env_file:
      - ../../../config/podverse-sandbox-keyvaldb.env
    networks:
      - podverse_sandbox_network
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - podverse_sandbox_keyvaldb_data:/var/lib/valkey
      - ../../../scripts/keyvaldb:/opt/keyvaldb
    command: ["/opt/keyvaldb/valkey-entrypoint.sh"]
    healthcheck:
      test: ["CMD", "/opt/keyvaldb/valkey-healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    logging:
      driver: "syslog"
      options:
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"

  podverse_sandbox_keyvaldb_gui:
    image: redislabs/redisinsight:latest
    container_name: podverse_sandbox_keyvaldb_gui
    ports:
      - '127.0.0.1:8001:5540'
    networks:
      - podverse_sandbox_network
    depends_on:
      - podverse_sandbox_keyvaldb
    restart: unless-stopped
