@startuml dataflow00
actor client

cloud [AWS] {
  node sqs
}

cloud [PODPING] {
  node hive
}

cloud [DigitalOcean] {
  
  node app
  node api_worker
database db
}

hive <-> api_worker


api_worker <-- sqs
api_worker <-> db
db <-> app
app <-> client


@enduml