@startuml vps00

cloud {
  [Internet]
}

node "Podverse" {
  [Internet] --> HTTP
  [Internet] --> HTTPS


  node "Docker Container WEB" {
    [nginx_proxy]
    [APPLICATION]
    [API]
  }
}

node "Podverse Droplet DB" {
  node "Docker Container DB" {
    database "PostGreSQL" {
      [database]
    }
  }
}
node "Podverse API Worker" {
  node "Docker Container API Worker" {
    node node0 [
      nodejs
      podping
    ]
    node node1 [
      nodejs
      podping
    ]
    node node2 [
      nodejs
      podping
    ]
    node node3 [
      nodejs
      podping
    ]
    node node4 [
      nodejs
      podping
    ]
    node node5 [
      nodejs
      podping
    ]
    node node6 [
      nodejs
      podping
    ]
    node node7 [
      nodejs
      podping
    ]
  }
}


HTTP --> [nginx_proxy]
HTTPS --> [nginx_proxy]
nginx_proxy --> [APPLICATION]
nginx_proxy --> [API]

[API] --> [database]
[APPLICATION] --> [database]
[node0] --> [database]
[node1] --> [database]
[node2] --> [database]
[node3] --> [database]
[node4] --> [database]
[node5] --> [database]
[node6] --> [database]
[node7] --> [database]

@enduml
