FROM mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm

LABEL org.opencontainers.image.source=https://github.com/podverse/podverse-ops
LABEL org.opencontainers.image.description="Podverse Web Devcontainer"
LABEL org.opencontainers.image.licenses=AGPLv3
