# Version: 1
# Filename: kustomization.yaml
# Description: Bundles the cron jobs and exposes the worker image tag via kustomize.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/cron/01-recent-feeds.yaml
  - ../../base/cron/02-archive-all.yaml
  - ../../base/cron/03-reports.yaml
  - ../../base/cron/04-dead-feeds-merge.yaml
  - ../../base/cron/05-delete-outdated.yaml
namespace: podverse-alpha

images:
  - name: ghcr.io/podverse/podverse-workers/podverse-workers
    newTag: "5.1.28-alpha.0"

labels:
  - pairs:
      app: podverse-cron
      environment: alpha
    # This ensures the labels are also applied to the selectors,
    # so the Service correctly finds the Pods.
    includeSelectors: true
