# Version: 2
# Filename: kustomization.yaml
# Description: Bundles resources and manages image versions for the API.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Resources to include
resources:
  - ../../base/api/01-configmap.yaml
  - ../../base/api/02-service.yaml
  - ../../base/api/03-deployment.yaml

# 2. Namespace (optional, ensures all resources are in this namespace)
namespace: podverse-alpha

# 3. Common Labels (Updated to modern 'labels' syntax)
# This tags all resources (Deployment, Service, ConfigMap) with these labels.
labels:
  - pairs:
      app: podverse-api
      environment: alpha
    # This ensures the labels are also applied to the selectors,
    # so the Service correctly finds the Pods.
    includeSelectors: true

# 3. ConfigMap overrides for alpha environment
configMapGenerator:
  - name: podverse-api-config
    behavior: merge
    literals:
      - API_ALLOWED_CORS_ORIGINS="http://podverse-web:3000,https://api-alpha-podverse.k.podverse.fm,https://alpha-podverse.k.podverse.fm,https://k.podverse.fm"
      - COOKIE_DOMAIN=".k.podverse.fm"
      - WEB_DOMAIN="alpha-podverse.k.podverse.fm"

patches:
  - path: deployment-link-patch.yaml

# 4. Image Variables
# We define the specific version here.
images:
  - name: ghcr.io/podverse/podverse-api/podverse-api
    newTag: "5.1.28-alpha.0"
